### ISSUE TITLE
Example code doesn't work since doesn't contain speed or heading?

### ISSUE THREAD

**Issue by Workings** [binateq/gps-track-filter#3]
Has the code changed since the example was generated, as doesn't seem to be working due to Double.IsNormal(x.Speed), or should we be pre calculating the gps speed before using the lib?

**Comment by markshevchenko** [comment]
> Has the code changed since the example was generated, as doesn't seem to be working due to Double.IsNormal(x.Speed), or should we be pre calculating the gps speed before using the lib?

Yes, the code has changed. Sorry for my inadvertence, I'll try to fix the example within a day.

**Comment by Workings** [comment]
No worries. Ended up grabbing speed and direction from gps and seems to work well, thanks.

**Comment by markshevchenko** [comment]
@Workings, you're right. `Double.IsNormal()` detects 0.0 as not-normal double number. As I understand, it's true, because 0.0 is formally sub-normal value. But I was confused a bit with the name of the method. I have always considered 0.0 to be a normal number.

Anyway, I have fixed the bug and increased target framework to the .NET 6.0.

Thank you for your feedback.
